{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "krabka-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "krabka-operator.labels" . | nindent 4 }}
{{- end }}
